### ISSUE TITLE
音乐收集整理列表 / Music collection list

### ISSUE THREAD

**Issue by neteroster** [neteroster/blog#1]
**Independent Music Collection List:**

[CD-ID (If existed)][Res-Type]CD-TITLE

**(Res-Type)[CD-Res]** Usually `.flac` + `.cue`; ~1000 kbps; ~44.1kHz
**(Res-Type)[Hi-Res]** Usually single `.flac` file; ~4000 kbps; ~96kHz

- [x] [KSLA-0059~60][CD-Res]Angel Beats! Original Soundtrack
    - [KSLA-0059][CD-Res]Angel Beats! Original Soundtrack (Disc 1)
    - [KSLA-0060][CD-Res]Angel Beats! Original Soundtrack (Disc 2)
- [x] [KSLA-176][CD-Res]君という神話
- [x] [GNCA-0309][CD-Res]lull\~そして僕らは\~(初回限定盤)
- [x] [GNCA-0316][CD-Res]アクアテラリウム(初回限定盤)
- [x] [GNCA-0323][CD-Res]ebb and flow(初回限定盤)
- [x] [GNCA-0325][CD-Res]三つ葉の結びめ
- [x] [GNCA-1404][CD-Res]凪のあすから ORIGINAL SOUNDTRACK 1
- [x] [GNCA-1405][CD-Res]凪のあすから ORIGINAL SOUNDTRACK 2
- [x] [GNCA-0605][CD-Res]ダイヤモンドの純度
- [x] [GNCA-0607][CD-Res]芽ぐみの雨
- [x] [SECL-949][CD-Res]コネクト
- [x] [SVWC-70516][CD-Res]ATRI -My Dear Moments- (Original Soundtrack)
- [x] [YSCD-0041~44][CD-Res]千恋_万花 キャラクターソング
    - [YSCD-0041][CD-Res]千恋_万花 キャラクターソング Vol.1 「とおりゃんせ~甘美風来」
    - [YSCD-0042][CD-Res]千恋_万花 キャラクターソング Vol.2 「茉子の日常」
    - [YSCD-0043][CD-Res]千恋_万花 キャラクターソング Vol.3 「キズナヒトツ」
    - [YSCD-0044][CD-Res]千恋_万花 キャラクターソング Vol.4 「Blue sky」
- [x] [YSCD-0045~47][CD-Res]千恋＊万花 オリジナルサウンドトラック
    - [YSCD-0045][CD-Res]千恋＊万花 オリジナルサウンドトラック(Disc 1)
    - [YSCD-0046][CD-Res]千恋＊万花 オリジナルサウンドトラック(Disc 2)
    - [YSCD-0047][CD-Res]千恋＊万花 オリジナルサウンドトラック(Disc 3)
- [x] [Single][CD-Res]Sweets Parade
- [x] [PCCG-01197][CD-Res]ゆりゆららららゆるゆり大事件(初回限定盤)
- [x] [PCCG-70120][CD-Res]マイペースでいきましょう
- [x] [SMRR-17][CD-Res]色違いの翼
- [x] [PCCG-01939][CD-Res]キミのとなりで
- [x] [PCCG-01929][CD-Res]君に会えた日
- [x] [1000529072][CD-Res]Animetic Love Letter
- [x] Angel Beats! ALL MUSIC COLLECTION 
    - [x] [KSLA-0054][CD-Res]TVアニメ「Angel Beats！」OP＆ED「My Soul，Your Beats！／Brave Song」
    - [x] [KSLA-0059~60][CD-Res]Angel Beats! Original Soundtrack
        - [KSLA-0059][CD-Res]Angel Beats! Original Soundtrack (Disc 1)
        - [KSLA-0060][CD-Res]Angel Beats! Original Soundtrack (Disc 2)
    - [x] Girls Dead Monster
        - [x] [KSLA-0051][CD-Res]TVアニメ「Angel Beats！」第1弾マキシシングル「Crow Song」
        - [x] [KSLA-0052][CD-Res]TVアニメ「Angel Beats！」第2弾マキシシングル「Thousand Enemies」
        - [x] [KSLA-0055][CD-Res]TVアニメ「Angel Beats！」第3弾マキシシングル「Little Braver」
        - [x] [KSLA-0058][CD-Res]TVアニメ「Angel Beats！」ボーカルアルバム「Keep The Beats！」
        - [x] [KSLA-0064][CD-Res]TVアニメ「Angel Beats！」第4弾マキシシングル「Last Song」
        - [x] [KSLA-0065][CD-Res]TVアニメ「Angel Beats！」第5弾マキシシングル「一番の宝物～Yui final ver.～」
        - [x] [SVWC-7721][CD-Res]TVアニメ「Angel Beats！」 Girls Dead Monster OFFICIAL BAND SCORE「Keep The Beats！」
- [x] [KSLA-0093][CD-Res]君とのなくしもの & 涙色の翼
- [x] [KSLA-0033~35][CD-Res]リトルバスターズ! Original Soundtrack
    - [x] [KSLA-0033][CD-Res]リトルバスターズ! Original Soundtrack (Disc 1)
    - [x] [KSLA-0034][CD-Res]リトルバスターズ! Original Soundtrack (Disc 2)
    - [x] [KSLA-0035][CD-Res]リトルバスターズ! Original Soundtrack (Disc 3)

**Task:**
- [ ] Separate all music from VCB-s collection.

Some music from VCB-s is not well ripped. Need more consideration.
